import type { IGraphQLConfig } from "graphql-config";

// Use locally cached schema file generated by `pnpm codegen`
// This avoids needing environment variables for IDE features
const config: IGraphQLConfig = {
  schema: "thor.schema.graphql",
  documents: ["src/**/*.graphql", "!src/generated/**"],
};

export default config;
