import mjml2html from 'mjml';
import Handlebars from 'handlebars';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Build script to compile MJML templates to HTML and precompile Handlebars
 * Run this before deployment: pnpm build:emails
 */

const templates = [
	'order-confirmation',
];

const emailsDir = join(__dirname, '../emails');
const outputDir = join(__dirname, '../src/emails/compiled');

// Create output directory
mkdirSync(outputDir, { recursive: true });

console.log('🔨 Compiling MJML + Handlebars templates...\n');

for (const template of templates) {
	const mjmlPath = join(emailsDir, `${template}.mjml`);
	const outputHtmlPath = join(outputDir, `${template}.html`);
	const outputJsPath = join(outputDir, `${template}.js`);
	
	try {
		// Step 1: Read MJML template
		const mjmlTemplate = readFileSync(mjmlPath, 'utf-8');
		
		// Step 2: Convert MJML to HTML
		const { html, errors } = mjml2html(mjmlTemplate, {
			validationLevel: 'soft',
		});
		
		if (errors.length > 0) {
			console.warn(`⚠️  Warnings for ${template}:`, errors);
		}
		
		// Step 3: Precompile HTML with Handlebars
		const precompiled = Handlebars.precompile(html);
		
		// Step 4: Write HTML (for reference)
		writeFileSync(outputHtmlPath, html, 'utf-8');
		
		// Step 5: Write precompiled template as JS module
		const jsModule = `// Auto-generated by build-emails.mjs
// Do not edit manually
export default ${precompiled};
`;
		writeFileSync(outputJsPath, jsModule, 'utf-8');
		
		console.log(`✅ Compiled ${template}.mjml → ${template}.js`);
	} catch (error) {
		console.error(`❌ Failed to compile ${template}:`, error);
		process.exit(1);
	}
}

console.log('\n✨ Email templates compiled successfully!');
